class Exception8{
public static void main(String args[]){
int a=10;
int b=0;
int c;
try{
c=a/b;
}
catch(Exception e){
int d=29/0;
}
System.out.println("rest of the code...");
}
}